# **Ahmet Selçuk KÜREN Staj Çalışmaları**
#**Numpy nedir ?**
NumPy, dizilerle çalışmak için kullanılan bir Python kütüphanesidir. Ayrıca doğrusal cebir, fourier dönüşümü ve matrisler alanında çalışmak için de gerekli işlevlere sahiptir.
# 1.   Numpy Özellikleri
 ## Yeniden Şekillendirme (Reshaping)
## Index Seçimi (Index Selection)
 ## Fancy Index



In [1]:
import numpy as np

**Numpy Array'i oluşturmak**

In [2]:
np.array([1, 2, 3, 4, 5])
type(np.array([1, 2, 3, 4, 5]))
np.zeros(10, dtype=int)
np.random.randint(0, 10, size=10)
np.random.normal(10, 4, (3, 4))

array([[ 9.43815846,  7.24848863, 15.15304038,  6.86681271],
       [11.55089265, 13.03597825,  7.28465472,  6.33441394],
       [ 8.52414064, 14.57279117,  6.70717507,  6.87843003]])

**NumPy Array Özellikleri (Attibutes of Numpy Arrays)**

In [8]:
a = np.random.randint(10, size=5)
a.ndim #ndim: boyut sayısı




1

In [5]:
a.shape # shape: boyut bilgisi

(5,)

In [6]:
a.size # size: toplam eleman sayısı

5

In [7]:
a.dtype # dtype: array veri tipi

dtype('int64')

**Yeniden Şekillendirme (Reshaping)**

In [10]:
np.random.randint(1, 10, size=9)

array([7, 4, 7, 9, 7, 3, 4, 9, 5])

In [11]:
ar = np.random.randint(1, 10, size=9)
ar.reshape(3, 3)

array([[2, 8, 9],
       [6, 7, 1],
       [1, 2, 9]])

reshape() fonkiyonu ile oluşturulan array'lerin matris boyutunda değişiklik yapabiliriz.

**Index Seçimi (Index Selection)**

In [14]:
a = np.random.randint(10, size=10)
a[0]# a nın sıfırıncı elemanını seçmemizi sağlar

4

In [16]:
a[0:5]# 0. elemandan 5. elemana kadar gösterir(5. eleman hariç)

array([4, 4, 2, 2, 3])

2 boyutlu matrislerde seçim işlemi

In [18]:
m = np.random.randint(10, size=(3, 5))
m

array([[0, 1, 1, 3, 2],
       [4, 5, 5, 7, 2],
       [8, 9, 0, 6, 8]])

In [19]:
m[1, 1] # 1. satır 1. sütündaki elemanı seçmemizi sağlar.

5

In [20]:
m[2, 3] # 2. satır 3. sütundaki elemanı seçmemizi sağlar.

6

**Fancy Index**

In [22]:
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

arange() fonksiyonu başlangıç , bitiş ve artış miktarı girilen değerleri array haline getirir.

In [25]:
catch = [1, 2, 3] #seçili indexteki elemanları getirir.
v[catch]

array([3, 6, 9])

**Matematiksel İşlemler (Mathematical Operations)**

In [27]:
z = np.array([1, 2, 3, 4, 5])
z

array([1, 2, 3, 4, 5])

In [29]:
z / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [30]:
z * 5 / 10

array([0.5, 1. , 1.5, 2. , 2.5])

In [31]:
z ** 2

array([ 1,  4,  9, 16, 25])